# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blackouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery', models.CharField(blank=True, db_column='BAKERY', max_length=40, null=True)),
                ('line_name', models.CharField(blank=True, db_column='LINE_NAME', max_length=40, null=True)),
                ('prod_type', models.CharField(blank=True, db_column='PROD_TYPE', max_length=40, null=True)),
                ('ibl', models.IntegerField(blank=True, db_column='IBL', null=True)),
                ('template_year', models.IntegerField(blank=True, db_column='TEMPLATE_YEAR', null=True)),
                ('submission_month', models.IntegerField(blank=True, db_column='SUBMISSION_MONTH', null=True)),
                ('submission_year', models.IntegerField(blank=True, db_column='SUBMISSION_YEAR', null=True)),
                ('line_number', models.IntegerField(blank=True, db_column='LINE_NUMBER', null=True)),
                ('jan_straight', models.IntegerField(blank=True, db_column='JAN_STRAIGHT', null=True)),
                ('jan_ot', models.IntegerField(blank=True, db_column='JAN_OT', null=True)),
                ('feb_straight', models.IntegerField(blank=True, db_column='FEB_STRAIGHT', null=True)),
                ('feb_ot', models.IntegerField(blank=True, db_column='FEB_OT', null=True)),
                ('mar_straight', models.IntegerField(blank=True, db_column='MAR_STRAIGHT', null=True)),
                ('mar_ot', models.IntegerField(blank=True, db_column='MAR_OT', null=True)),
                ('apr_straight', models.IntegerField(blank=True, db_column='APR_STRAIGHT', null=True)),
                ('apr_ot', models.IntegerField(blank=True, db_column='APR_OT', null=True)),
                ('may_straight', models.IntegerField(blank=True, db_column='MAY_STRAIGHT', null=True)),
                ('may_ot', models.IntegerField(blank=True, db_column='MAY_OT', null=True)),
                ('jun_straight', models.IntegerField(blank=True, db_column='JUN_STRAIGHT', null=True)),
                ('jun_ot', models.IntegerField(blank=True, db_column='JUNE_OT', null=True)),
                ('jul_straight', models.IntegerField(blank=True, db_column='JUL_STRAIGHT', null=True)),
                ('jul_ot', models.IntegerField(blank=True, db_column='JUL_OT', null=True)),
                ('aug_straight', models.IntegerField(blank=True, db_column='AUG_STRAIGHT', null=True)),
                ('aug_ot', models.IntegerField(blank=True, db_column='AUG_OT', null=True)),
                ('sep_straight', models.IntegerField(blank=True, db_column='SEP_STRAIGHT', null=True)),
                ('sep_ot', models.IntegerField(blank=True, db_column='SEP_OT', null=True)),
                ('oct_straight', models.IntegerField(blank=True, db_column='OCT_STRAIGHT', null=True)),
                ('oct_ot', models.IntegerField(blank=True, db_column='OCT_OT', null=True)),
                ('nov_straight', models.IntegerField(blank=True, db_column='NOV_STRAIGHT', null=True)),
                ('nov_ot', models.IntegerField(blank=True, db_column='NOV_OT', null=True)),
                ('dec_straight', models.IntegerField(blank=True, db_column='DEC_STRAIGHT', null=True)),
                ('dec_ot', models.IntegerField(blank=True, db_column='DEC_OT', null=True)),
            ],
        ),
    ]
