# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-29 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackout', '0006_auto_20160529_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sub_month',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
