# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-29 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackout', '0007_document_sub_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
