# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackout', '0010_auto_20160605_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackouts',
            name='upload_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
