# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 10:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackout', '0011_blackouts_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackouts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
