# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackout', '0013_blackouts_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackouts',
            name='file_name',
        ),
        migrations.AddField(
            model_name='blackouts',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
