# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackout', '0014_auto_20160605_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackouts',
            name='template_file',
        ),
    ]
