# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-06 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackout', '0015_remove_blackouts_template_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackouts',
            name='template_file',
            field=models.CharField(blank=True, db_column='TEMPLATE_FILE', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='blackouts',
            name='uploader',
            field=models.CharField(blank=True, db_column='UPLOADER', max_length=40, null=True),
        ),
    ]
