# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.PositiveIntegerField(default=0, verbose_name='interaction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('user',),
                'verbose_name_plural': 'Profiles',
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='SKU_FCST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_column='SKU', max_length=30, null=True)),
                ('calmonth', models.IntegerField(blank=True, db_column='CALMONTH', null=True)),
                ('calyear', models.IntegerField(blank=True, db_column='CALYEAR', null=True)),
                ('cases', models.IntegerField(blank=True, db_column='CASES', null=True)),
                ('pounds', models.FloatField(blank=True, db_column='POUNDS', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKU_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, db_column='KGF_STD_ITEM_CDE', max_length=14, null=True)),
                ('short_description', models.CharField(blank=True, db_column='SHORT_DESCRIPTION', max_length=40, null=True)),
                ('gross_wt_cse_qty', models.CharField(blank=True, db_column='GROSS_WT_CSE_QTY', max_length=40, null=True)),
                ('cube_adjusted_wt', models.CharField(blank=True, db_column='CUBE_ADJUSTED_WT', max_length=40, null=True)),
                ('case_per_mfg_stack', models.CharField(blank=True, db_column='CASE_PER_MFG_STACK', max_length=40, null=True)),
                ('net_wt_cse_qty', models.CharField(blank=True, db_column='NET_WT_CSE_QTY', max_length=40, null=True)),
                ('std_itm_cd', models.CharField(blank=True, db_column='STD_ITM_CD', max_length=40, null=True)),
                ('capacity_grp_cd', models.CharField(blank=True, db_column='CAPACITY_GRP_CD', max_length=40, null=True)),
            ],
        ),
    ]
