# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skulist', '0003_sku_fcst_sku_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SKU_FCST',
        ),
        migrations.DeleteModel(
            name='SKU_INFO',
        ),
    ]
